### ISSUE TITLE
Model format issue

### ISSUE THREAD

**Issue by H-cool** [IST-DASLab/SparseFinetuning#2]
Hello, in the given teacher fine-tuning code mpt-7b-arc-easy--gpu.yaml, the format of the saved fine-tuning model is .pt, but the requirement for the teacher model during the distillation process is .bin. During the process of distilling and importing the teacher model, if the .pt format is used, an error will be reported. How did you solve this problem? Thank you for your answer.

**Comment by eldarkurtic** [comment]
The ".pt" format is the format that llm-foundry is using by default to save the model weights, optimizer, state of schedulers, etc. In order to get the ".bin" format that is used to load the teacher model for sparse-finetuning you need to extract only weights and convert them to HuggingFace-friendly format. For that, please use the following script https://github.com/IST-DASLab/SparseFinetuning/blob/main/scripts/inference/convert_composer_to_hf.py 

`python convert_composer_to_hf.py --composer_path <your_pt_checkpoint> --hf_output_path my_hf_model/ --output_precision bf16`
